# Generated by Django 5.0.7 on 2024-09-14 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.TextField(max_length=200)),
                ('song_image', models.FileField(upload_to='media/uploads')),
                ('spotify_link', models.CharField(max_length=200)),
                ('soundcloud_link', models.CharField(max_length=600)),
                ('applemusic_link', models.CharField(max_length=600)),
                ('audiomack', models.CharField(max_length=600)),
                ('tidal', models.CharField(max_length=600)),
                ('youtube', models.CharField(max_length=600)),
                ('date_added', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
