# Generated by Django 5.0.7 on 2024-09-14 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='album_title',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AddField(
            model_name='music',
            name='video',
            field=models.FileField(default=None, upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song_image',
            field=models.FileField(default=None, upload_to='media/uploads'),
        ),
    ]
