# Generated by Django 5.0.7 on 2024-09-14 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0003_alter_music_song_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='album_title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='applemusic_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='audiomack',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='date_added',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='song_image',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='music',
            name='song_title',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='soundcloud_link',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='spotify_link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='tidal',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
        migrations.AlterField(
            model_name='music',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='media/uploads'),
        ),
        migrations.AlterField(
            model_name='music',
            name='youtube',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
