# Generated by Django 5.0.7 on 2024-09-14 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0004_alter_music_album_title_alter_music_applemusic_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='artist_name',
            field=models.CharField(blank=True, default=None, max_length=200, null=True),
        ),
    ]
