# Generated by Django 5.0.7 on 2024-09-14 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0005_music_artist_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Albums',
            },
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name_plural': 'Music'},
        ),
        migrations.AlterField(
            model_name='music',
            name='album_title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artist.album'),
        ),
    ]
