# Generated by Django 5.0.7 on 2024-09-14 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0007_alter_music_album_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'verbose_name_plural': 'Album'},
        ),
        migrations.RemoveField(
            model_name='music',
            name='album_title',
        ),
    ]
