# Generated by Django 5.0.7 on 2024-09-14 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0008_alter_album_options_remove_music_album_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Album',
        ),
        migrations.DeleteModel(
            name='Music',
        ),
    ]
