# Generated by Django 5.0.7 on 2024-09-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artist', '0009_delete_album_delete_music'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.CharField(blank=True, default=None, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': 'Album',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('artist_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('song_image', models.FileField(blank=True, default=None, null=True, upload_to='media/uploads')),
                ('video', models.FileField(blank=True, default=None, null=True, upload_to='media/uploads')),
                ('spotify_link', models.CharField(blank=True, max_length=200, null=True)),
                ('soundcloud_link', models.CharField(blank=True, max_length=600, null=True)),
                ('applemusic_link', models.CharField(blank=True, max_length=600, null=True)),
                ('audiomack', models.CharField(blank=True, max_length=600, null=True)),
                ('tidal', models.CharField(blank=True, max_length=600, null=True)),
                ('youtube', models.CharField(blank=True, max_length=600, null=True)),
                ('date_added', models.DateTimeField(auto_now=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Music',
            },
        ),
    ]
