# Generated by Django 5.0.7 on 2024-09-14 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0011_music_album_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewReleases',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_title', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('artist_name', models.CharField(blank=True, default=None, max_length=200, null=True)),
                ('song_image', models.FileField(blank=True, default=None, null=True, upload_to='media/uploads')),
                ('song_video', models.FileField(blank=True, default=None, null=True, upload_to='media/uploads')),
                ('album_title', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='artist.album')),
            ],
            options={
                'verbose_name_plural': 'NewReleases',
            },
        ),
    ]
